name: 多平台构建

on: 
  # 触发条件，这里我是手动的，可以配置push自动触发
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU # 模拟器，模拟不同平台
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx # 通过Buildx，构建多平台
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub # 这里要登陆Docker Hub，需要账户名和一个token，token去Docker Hub生成，然后要在Github项目设置里添加两个secrets，DOCKERHUB_USERNAME 和 DOCKERHUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push # 构建推送
        uses: docker/build-push-action@v4
        with:
          context: .  # 这里在项目根目录找Dockerfile构建
          platforms: linux/amd64,linux/arm64,linux/arm # 可配置多个平台
          push: true 
          tags: hslr/sun-panel-docker-build-test # 这里要改成你的Docker Hub 名字
